import fs from 'node:fs'
import assert from 'node:assert/strict'

const layout = fs.readFileSync(new URL('../layouts/DefaultLayout.vue', import.meta.url), 'utf8')
const router = fs.readFileSync(new URL('../router/index.ts', import.meta.url), 'utf8')
const artifactList = fs.readFileSync(new URL('../views/ArtifactListView.vue', import.meta.url), 'utf8')
const artifactBatches = fs.readFileSync(new URL('../views/ArtifactBatchesView.vue', import.meta.url), 'utf8')
const artifactVersionDetail = fs.readFileSync(new URL('../views/ArtifactVersionDetailView.vue', import.meta.url), 'utf8')
const batchDeploy = fs.readFileSync(new URL('../views/BatchDeployView.vue', import.meta.url), 'utf8')
const artifactCollect = fs.readFileSync(new URL('../views/ArtifactCollectView.vue', import.meta.url), 'utf8')
const kubernetesView = fs.readFileSync(new URL('../views/KubernetesView.vue', import.meta.url), 'utf8')
const kubernetesApi = fs.readFileSync(new URL('../api/kubernetes.ts', import.meta.url), 'utf8')

assert.match(layout, /<span>制品管理<\/span>/, 'sidebar should expose 制品管理 as a menu group')
assert.doesNotMatch(layout, /<template #title>制品记录<\/template>/, 'sidebar should not expose 制品记录 as a separate entry')
assert.match(layout, /index="\/artifacts\/import"[^>]*>制品导入</, 'sidebar should expose 制品导入 as an artifact submenu')
assert.match(layout, /index="\/artifacts\/versions"[^>]*>更新版本</, 'sidebar should expose 更新版本 as an artifact submenu')
assert.match(layout, /index="\/artifacts\/latest"[^>]*>最新制品库</, 'sidebar should expose 最新制品库 as an artifact submenu')

assert.match(router, /path: 'artifacts', redirect: '\/artifacts\/latest'/, 'artifacts root should redirect to latest library')
assert.match(router, /path: 'artifacts\/import'.+meta: \{ title: '制品导入'/s, 'artifact import should have a standalone route')
assert.match(router, /path: 'artifacts\/versions'.+meta: \{ title: '更新版本'/s, 'artifact versions should have a standalone route')
assert.match(router, /path: 'artifacts\/latest'.+meta: \{ title: '最新制品库'/s, 'latest artifact library should have a standalone route')
assert.match(router, /path: 'artifact-collect', redirect: '\/artifacts\/import'/, 'old collection route should redirect to import page')
assert.match(router, /path: 'artifact-batches', redirect: '\/artifacts\/versions'/, 'old batches route should redirect to versions page')
assert.match(router, /path: 'artifacts\/versions\/:versionNo'/, 'version detail should have a standalone route')

assert.doesNotMatch(artifactList, /<el-tabs|el-tab-pane/, 'latest artifact page should not host import/version tabs')
assert.doesNotMatch(artifactList, /label="制品上传"/, 'artifact management tab should not be named 制品上传')
assert.doesNotMatch(artifactList, /label="更新批次"/, 'artifact management tab should not be named 更新批次')

assert.match(artifactBatches, />详情</, 'artifact versions should enter detail rather than deploy directly')
assert.doesNotMatch(artifactBatches, /进入部署/, 'artifact versions should not expose deploy action')
assert.doesNotMatch(artifactBatches, /path:\s*['"]\/batch-deploy['"]|router\.push\([^)]*\/batch-deploy/, 'artifact versions should not route to deployment')

assert.match(artifactVersionDetail, /应用匹配/, 'version detail should show application matching')
assert.match(artifactVersionDetail, /校验状态/, 'version detail should show validation status')
assert.match(artifactVersionDetail, /删除制品/, 'version detail should allow deleting a bad artifact item')
assert.match(artifactVersionDetail, /重新上传/, 'version detail should allow replacing a bad artifact item')
assert.match(artifactVersionDetail, /部署目标/, 'version detail should show deployment target grouping')
assert.match(artifactVersionDetail, /label="部署目标"[\s\S]*label="文件名"/, 'deployment target should be the first artifact table column before file name')
assert.match(artifactVersionDetail, /label="容器内路径"/, 'version detail should label artifact destination as container path')
assert.doesNotMatch(artifactVersionDetail, /label="部署路径"/, 'version detail should not call container paths deployment paths')
assert.match(artifactVersionDetail, /artifactSpanMethod/, 'artifact detail table should merge repeated deployment target cells')
assert.doesNotMatch(artifactVersionDetail, /部署目标：/, 'artifact detail should not render a synthetic deployment target row')
assert.match(artifactVersionDetail, /\/opt\/app\.jar/, 'java artifacts should show the final jar path inside the container')
assert.match(artifactVersionDetail, /\/usr\/share\/nginx\/html/, 'vue main artifacts should show the final html path inside the container')
assert.match(artifactVersionDetail, /\/usr\/share\/nginx\/html\/apps\//, 'web-main child artifacts should show the final child app path inside the container')
assert.match(artifactVersionDetail, /当前状态/, 'version detail should label runtime preview records as current status')
assert.match(artifactVersionDetail, /当前版本尚未部署/, 'version detail should explain current runtime preview before deployment')
assert.match(artifactVersionDetail, /const deployLoading = ref\(false\)/, 'runtime deploy preview should have its own loading state')
assert.doesNotMatch(artifactVersionDetail, /await loadDeployBatch\(\)/, 'version detail should not block initial page render on slow runtime preview')
assert.match(artifactVersionDetail, /function formatRawJson/, 'deploy records should render raw JSON returned by the API')
assert.doesNotMatch(artifactVersionDetail, /function formatBusinessVersion/, 'deploy records should not collapse business version JSON into a lossy summary')
assert.doesNotMatch(artifactVersionDetail, /currentBusinessVersion/, 'deploy records should not add a computed current version column that duplicates update-before data')
assert.match(artifactVersionDetail, /const deployRecordRows = computed/, 'deploy records should normalize rows before rendering')
assert.match(artifactVersionDetail, /deployRecordSpanMethod/, 'deploy records should merge repeated deployment target cells like artifact rows')
assert.match(artifactVersionDetail, /label="部署目标"[\s\S]*label="制品"/, 'deployment target should be the first deploy record table column')
assert.doesNotMatch(artifactVersionDetail, /label="当前版本"/, 'deploy records should not display a duplicate current version column')

assert.match(batchDeploy, /listArtifactVersions/, 'batch deploy should load persisted update versions')
assert.match(batchDeploy, /getArtifactVersion/, 'batch deploy should read version items from detail API')
assert.doesNotMatch(batchDeploy, /listLocalDir|matchArtifacts/, 'batch deploy should not rescan directories or run match side effects')
assert.match(batchDeploy, /选择更新版本/, 'batch deploy should let users select an update version')
assert.match(batchDeploy, /卡点部署/, 'deploy mode should be configured on batch deploy page')

assert.match(artifactCollect, /importMode/, 'artifact import should have an explicit import mode')
assert.match(artifactCollect, /v-if="importMode === 'upload'"/, 'artifact import should only show local upload when upload mode is selected')
assert.match(artifactCollect, /v-if="importMode === 'download'"/, 'artifact import should only show server download when download mode is selected')
assert.match(artifactCollect, /远程目录/, 'server download mode should show the remote source directory')
assert.match(artifactCollect, /本地目录/, 'server download mode should show the local target directory')
assert.match(artifactCollect, /downloadStatusText|downloadPercent/, 'server download mode should expose visible download progress')
assert.doesNotMatch(artifactCollect, /collect-grid/, 'artifact import should not show upload and download panels side by side')

assert.match(kubernetesApi, /syncK8sDeploymentRuntimeVersions/, 'kubernetes API should expose runtime version sync')
assert.match(kubernetesView, /deploymentRuntimeVersions/, 'deployment page should keep cached runtime versions from the API')
assert.match(kubernetesView, /label="版本"/, 'deployment table should show a runtime business version column')
assert.match(kubernetesView, /同步版本/, 'deployment page should let operators sync runtime versions into the database')
assert.match(kubernetesView, /formatRuntimeVersionDetails/, 'deployment version popover should render full runtime version fields instead of a lossy one-line string')
assert.match(kubernetesView, /完整版本数据/, 'deployment version popover should expose the complete business version JSON')
assert.doesNotMatch(kubernetesView, /return `\$\{branch\} \/ \$\{id\} \/ \$\{time\}`/, 'deployment version display should not collapse git info into a hard-to-read one-line string')
assert.match(kubernetesView, /const deploymentTableRows = computed/, 'deployment page should render flattened one-to-many rows for web-main')
assert.match(kubernetesView, /deploymentTableSpanMethod/, 'deployment page should merge deployment-level cells across web-main child rows')
assert.match(kubernetesView, /label="Deployment"/, 'deployment table should keep deployment as the first merged column')
assert.doesNotMatch(kubernetesView, /label="web-main\/子系统ID"/, 'deployment table should not expose web-main child id as a separate column')
assert.match(kubernetesView, /label="业务应用"/, 'deployment table should keep a single business app column')
assert.match(kubernetesView, /businessAppDisplay/, 'business app column should include web-main child id when applicable')
assert.match(kubernetesView, /label="Commit"/, 'deployment table should split commit from branch and version')
assert.match(kubernetesView, /openRuntimeVersionDialog/, 'deployment rows should open full runtime version JSON from a row action')
assert.doesNotMatch(kubernetesView, /runtime-version-popover/, 'deployment page should not hide high-frequency web-main child versions behind hover popovers')
assert.match(artifactVersionDetail, /openVersionJsonDialog/, 'version detail should open full JSON in a readable dialog')
assert.match(artifactVersionDetail, /完整版本数据/, 'version detail should label full API-returned version data clearly')
assert.doesNotMatch(artifactVersionDetail, /<pre class="json-cell">\{\{ formatRawJson\(row\.(packageVersionJson|beforeBusinessVersionJson|afterBusinessVersionJson|restoredBusinessVersionJson)\) \}\}<\/pre>/, 'deploy record table should not dump raw JSON directly into narrow cells')
