import fs from 'node:fs'
import assert from 'node:assert/strict'

const layout = fs.readFileSync(new URL('../layouts/DefaultLayout.vue', import.meta.url), 'utf8')
const router = fs.readFileSync(new URL('../router/index.ts', import.meta.url), 'utf8')
const artifactList = fs.readFileSync(new URL('../views/ArtifactListView.vue', import.meta.url), 'utf8')
const artifactBatches = fs.readFileSync(new URL('../views/ArtifactBatchesView.vue', import.meta.url), 'utf8')
const artifactVersionDetail = fs.readFileSync(new URL('../views/ArtifactVersionDetailView.vue', import.meta.url), 'utf8')
const batchDeploy = fs.readFileSync(new URL('../views/BatchDeployView.vue', import.meta.url), 'utf8')
const artifactCollect = fs.readFileSync(new URL('../views/ArtifactCollectView.vue', import.meta.url), 'utf8')

assert.match(layout, /<span>制品管理<\/span>/, 'sidebar should expose 制品管理 as a menu group')
assert.doesNotMatch(layout, /<template #title>制品记录<\/template>/, 'sidebar should not expose 制品记录 as a separate entry')
assert.match(layout, /index="\/artifacts\/import"[^>]*>制品导入</, 'sidebar should expose 制品导入 as an artifact submenu')
assert.match(layout, /index="\/artifacts\/versions"[^>]*>更新版本</, 'sidebar should expose 更新版本 as an artifact submenu')
assert.match(layout, /index="\/artifacts\/latest"[^>]*>最新制品库</, 'sidebar should expose 最新制品库 as an artifact submenu')

assert.match(router, /path: 'artifacts', redirect: '\/artifacts\/latest'/, 'artifacts root should redirect to latest library')
assert.match(router, /path: 'artifacts\/import'.+meta: \{ title: '制品导入'/s, 'artifact import should have a standalone route')
assert.match(router, /path: 'artifacts\/versions'.+meta: \{ title: '更新版本'/s, 'artifact versions should have a standalone route')
assert.match(router, /path: 'artifacts\/latest'.+meta: \{ title: '最新制品库'/s, 'latest artifact library should have a standalone route')
assert.match(router, /path: 'artifact-collect', redirect: '\/artifacts\/import'/, 'old collection route should redirect to import page')
assert.match(router, /path: 'artifact-batches', redirect: '\/artifacts\/versions'/, 'old batches route should redirect to versions page')
assert.match(router, /path: 'artifacts\/versions\/:versionNo'/, 'version detail should have a standalone route')

assert.doesNotMatch(artifactList, /<el-tabs|el-tab-pane/, 'latest artifact page should not host import/version tabs')
assert.doesNotMatch(artifactList, /label="制品上传"/, 'artifact management tab should not be named 制品上传')
assert.doesNotMatch(artifactList, /label="更新批次"/, 'artifact management tab should not be named 更新批次')

assert.match(artifactBatches, />详情</, 'artifact versions should enter detail rather than deploy directly')
assert.doesNotMatch(artifactBatches, /进入部署/, 'artifact versions should not expose deploy action')
assert.doesNotMatch(artifactBatches, /path:\s*['"]\/batch-deploy['"]|router\.push\([^)]*\/batch-deploy/, 'artifact versions should not route to deployment')

assert.match(artifactVersionDetail, /应用匹配/, 'version detail should show application matching')
assert.match(artifactVersionDetail, /校验状态/, 'version detail should show validation status')
assert.match(artifactVersionDetail, /删除制品/, 'version detail should allow deleting a bad artifact item')
assert.match(artifactVersionDetail, /重新上传/, 'version detail should allow replacing a bad artifact item')
assert.match(artifactVersionDetail, /部署目标/, 'version detail should show deployment target grouping')
assert.match(artifactVersionDetail, /label="部署目标"[\s\S]*label="文件名"/, 'deployment target should be the first artifact table column before file name')
assert.match(artifactVersionDetail, /label="容器内路径"/, 'version detail should label artifact destination as container path')
assert.doesNotMatch(artifactVersionDetail, /label="部署路径"/, 'version detail should not call container paths deployment paths')
assert.match(artifactVersionDetail, /artifactSpanMethod/, 'artifact detail table should merge repeated deployment target cells')
assert.doesNotMatch(artifactVersionDetail, /部署目标：/, 'artifact detail should not render a synthetic deployment target row')
assert.match(artifactVersionDetail, /\/opt\/app\.jar/, 'java artifacts should show the final jar path inside the container')
assert.match(artifactVersionDetail, /\/usr\/share\/nginx\/html/, 'vue main artifacts should show the final html path inside the container')
assert.match(artifactVersionDetail, /\/usr\/share\/nginx\/html\/apps\//, 'web-main child artifacts should show the final child app path inside the container')

assert.match(batchDeploy, /listArtifactVersions/, 'batch deploy should load persisted update versions')
assert.match(batchDeploy, /getArtifactVersion/, 'batch deploy should read version items from detail API')
assert.doesNotMatch(batchDeploy, /listLocalDir|matchArtifacts/, 'batch deploy should not rescan directories or run match side effects')
assert.match(batchDeploy, /选择更新版本/, 'batch deploy should let users select an update version')
assert.match(batchDeploy, /卡点部署/, 'deploy mode should be configured on batch deploy page')

assert.match(artifactCollect, /importMode/, 'artifact import should have an explicit import mode')
assert.match(artifactCollect, /v-if="importMode === 'upload'"/, 'artifact import should only show local upload when upload mode is selected')
assert.match(artifactCollect, /v-if="importMode === 'download'"/, 'artifact import should only show server download when download mode is selected')
assert.match(artifactCollect, /远程目录/, 'server download mode should show the remote source directory')
assert.match(artifactCollect, /本地目录/, 'server download mode should show the local target directory')
assert.match(artifactCollect, /downloadStatusText|downloadPercent/, 'server download mode should expose visible download progress')
assert.doesNotMatch(artifactCollect, /collect-grid/, 'artifact import should not show upload and download panels side by side')
